export const STORAGE_KEY = {
  USERS: "USERS",
  PROFILE_ID: "PROFILE_ID",
  BRANCH_ID: "BRANCH_ID",
  PROFILE_DETAILS: "PROFILE_DETAILS",
  MESSAGES: "MESSAGES",
  TOKEN: "TOKEN",
  ITEM_TYPES: "ITEM_TYPES",
  ITEMS: "ITEMS",
  ORDERS: "ORDERS",
  ORDER_TYPE: "ORDER_TYPE",
  SAVED_ORDER: "SAVED_ORDER",
};
